{% set name = "bempp-cl" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bempp/bempp-cl/archive/v{{ version }}.tar.gz
  sha256: b0cc0383f25ba62caa23013e616c64b816fd5b63626bf737577ae34fd8f002c6
build:
  number: 0
  skip: true  # [py<38]
  skip: true  # [win]
  skip: true  # [linux32]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - numba >=0.51.2
    - pocl >=1.5  # [not osx]
    - pyopencl >=2020.2.1  # [not osx]
    - meshio >=4.1.1
    - plotly
    - gmsh

test:
  imports:
    - bempp.api

about:
  home: https://github.com/bempp/bempp-cl
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: The Bempp-cl boundary element library.
  description: |
    Bempp-cl is a an OpenCL based boundary element library for Python.
  dev_url: https://github.com/bempp/bempp-cl

extra:
  recipe-maintainers:
    - tbetcke
